version: '3'

services:
  massivesearch-datasette:
    ports:
      - "8475:8475" # This port selection of the internal port matching the external port of the web server is to get around a datasette bug
    image: datasetteproject/datasette:0.58.1
    volumes:
      - ./database/:/app/database:ro
    networks:
      - nginx-net
      - default
    restart: on-failure
    command: datasette -p 8475 -h 0.0.0.0 --setting max_returned_rows 50000 --setting sql_time_limit_ms 30000 --setting max_csv_mb 0 /app/database/out-main_merged_psms.db

networks:
  nginx-net:
    external:
      name: nginx-net